name: kampd_shorts
description: A short videos app build for https://www.kampd.com/ assignment
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18
  video_player: ^2.5.2

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
flutter:
  uses-material-design: true
  generate: true
